from setuptools import setup, find_packages

setup(
    name="engineering-doc-review-system",
    version="0.1.0",
    description="AI/ML system for verifying vendor GA drawings against instrument datasheets",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "pytesseract==0.3.10",
        "Pillow==10.0.0",
        "opencv-python==4.8.0.74",
        "PyPDF2==3.0.1",
        "pdfplumber==0.9.0",
        "spacy==3.6.1",
        "sentence-transformers==2.2.2",
        "fuzzywuzzy==0.18.0",
        "python-Levenshtein==0.21.1",
        "scikit-learn==1.3.0",
        "numpy==1.24.3",
        "scipy==1.11.1",
        "faiss-cpu==1.7.4",
        "fastapi==0.100.0",
        "uvicorn==0.23.2",
        "streamlit==1.26.0",
        "pydantic==2.0.2",
        "sqlalchemy==2.0.20",
        "reportlab==4.0.4",
        "weasyprint==58.1",
        "matplotlib==3.7.2",
        "plotly==5.15.0",
        "python-dotenv==1.0.0",
        "pyyaml==6.0",
        "requests==2.31.0",
        "pandas==2.0.3",
        "loguru==0.7.0",
    ],
    entry_points={
        "console_scripts": [
            "edrs=main:main",
        ],
    },
)